[package]
name = "server"
version = "0.1.0"
authors = ["cloudybyte <hi@cloudybyte.net>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
actix = "0.10"
actix-web = "3"
actix-web-actors = "3"
async-graphql = "2.9.7"
async-graphql-actix-web = "2.9.7"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3.15"
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8"
slab = "0.4.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sodiumoxide = "0.2"
sqlx = { version = "0.4", features = ["chrono", "macros", "migrate", "offline", "postgres", "runtime-actix-rustls", "uuid"] }
thiserror = "1"
toml = "0.5"
uuid = { version = "0.8", features = ["serde", "v4"] }
starwars = { path = "crates/starwars" }