[package]
name = "server"
version = "0.1.0"
authors = ["cloudybyte <hi@cloudybyte.net>",
    "Erik Tesar <erik@erik-tesar.com>",
]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
actix = "0.10"
actix-web = "3"
async-graphql = { git = "https://github.com/minkan-chat/async-graphql.git" }
async-graphql-actix-web = { git = "https://github.com/minkan-chat/async-graphql.git" } 
log = "0.4"
pretty_env_logger = "0.4"
thiserror = "1"
toml = "0.5"
sqlx = { version = "0.4", features = ["chrono", "macros", "migrate", "offline", "postgres", "runtime-actix-rustls", "uuid"] }
serde = "1"
serde_cbor = "0.11"
serde_json = "1.0.66"
uuid = { version = "0.8", features = ["serde", "v4"] }
bytes = "1"
